name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - 
        name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jucandia/python_app:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # ðŸ”¹ STEP NUEVO: instalar yq (igual que en el pod)
      - name: Install yq (no root)
        shell: bash
        run: |
          mkdir -p ~/.local/bin
          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o ~/.local/bin/yq
          chmod +x ~/.local/bin/yq
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          yq --version

      - name: Modify Values file
        shell: bash
        run: |
          echo ${{ needs.ci.outputs.commit_id }}

          yq -e '.image.tag = "${{ needs.ci.outputs.commit_id }}"'  charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update values.yaml with commit ${{ needs.ci.outputs.commit_id }}'

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: ArgoCD login
        run: |
          argocd login argocd-server.argocd:80 \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --plaintext \
            --grpc-web

      - name: ArgoCD app sync
        run: |
          argocd app sync python-aa
